CREATE DATABASE IF NOT EXISTS live;
USE live;

CREATE TABLE IF NOT EXISTS users (
  id          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id     VARCHAR(256) NOT NULL
  user_name   VARCHAR(256) NOT NULL,
  img         VARCHAR(256) NULL,
  password    VARCHAR(256) NOT NULL
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;