CREATE DATABASE IF NOT EXISTS live;
USE live;

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id`          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `uuid`        VARCHAR(256) NOT NULL,
  `user_id`     VARCHAR(256) UNIQUE NOT NULL,
  `user_name`   VARCHAR(256) NOT NULL,
  `img`         VARCHAR(256) NULL,
  `password`    VARCHAR(256) NOT NULL,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `followers`;
CREATE TABLE IF NOT EXISTS `followers` (
  `user_id`      VARCHAR(256) UNIQUE NOT NULL,
  `user_name`    VARCHAR(256) NOT NULL,
  `user_img`     VARCHAR(256) NOT NULL,
  `follower`     VARCHAR(256) NOT NULL,
  `following`    VARCHAR(256) NOT NULL,
  `is_following` BOOLEAN
)